### ISSUE TITLE
Variants don’t apply styles correctly with keys like “1/2”, “3/4"

### ISSUE THREAD

**Issue by my-slab** [stitchesjs/stitches#1064] opened 2022-07-17 10:43 UTC
# Bug report

## Describe the bug

`variants` don’t apply styles correctly with rules like:

```
const failVariants = css({
  display: "grid",
  gap: "16px",
  padding: "8px",
  variants: {
    fraction: {
      "1/4": { gridTemplateColumns: "1fr 3fr" },
      "1/2": { gridTemplateColumns: "1fr 1fr" }
    }
  }
});
```

## To Reproduce

[CodeSandbox Example](https://codesandbox.io/s/happy-architecture-b6qhk8?file=/src/App.tsx)

## Expected behavior

`variants` work with keys like, `1/4`, `1/2`.

## Additional context

I know [this article](https://stitches.dev/docs/tokens#naming-convention) exists for naming theme tokens, but I’m not sure if those rules are meant to apply to `variants` too.

**Comment by LexSwed** [comment] 2022-07-17 12:38
This is by design at the moment: https://stitches.dev/docs/tokens#naming-convention

**Comment by my-slab** [comment] 2022-07-18 00:11
Yep, I saw that and the linked discussion in https://github.com/stitchesjs/stitches/issues/493#issuecomment-801241038, but as far as I can tell that only applies to theme tokens? Do these conventions apply to variants too?

**Comment by LexSwed** [comment] 2022-07-18 07:43
Ah, sorry, my bad. I agree with you, seems like a bug, the class is generated correctly, but the styles aren't attached 👍

**Comment by hadihallak** [comment] 2022-07-27 18:31
That's pretty much is a duplicate of https://github.com/stitchesjs/stitches/issues/923 and https://github.com/stitchesjs/stitches/issues/731 
You can see more read more discussion about it in the latter 

Will be closing this issue for now as we have #932 to track it.

**Closed by hadihallak** 2022-07-27 18:31 UTC
