### ISSUE TITLE
Component composition is broken

### ISSUE THREAD

**Issue by marvinklein** [stitchesjs/stitches#1071] opened 2022-08-09 17:50 UTC
# Bug report

## Describe the bug

Component composition doesn’t work as expected in this trivial example:

```
import { styled } from "@stitches/react";

const A = styled("div", { color: "red" });
const B = styled(A, { color: "blue" });
const C = styled(B, { color: "red" });

export default function App() {
  return (
    <>
      <A>is red</A>
      <B>is blue</B>
      <C>expected to be red, but is blue!</C>
    </>
  );
}
```

## To Reproduce

https://codesandbox.io/s/charming-frost-lmqp5y?file=/src/App.js

**Comment by azuline** [comment] 2022-08-09 20:40
I think the root cause of this is #1039?

**Comment by hadihallak** [comment] 2022-10-06 18:03
Duplicate of https://github.com/stitchesjs/stitches/issues/1039

**Closed by hadihallak** 2022-10-06 18:03 UTC
